// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":       "src-5fe55569da16169e",
		"oceanbase":     "src-58ac48bd63438274",
		"diros":         "src-a46912c1f6357fec",
		"starrocks":     "src-8c0cb8e2e7c50b7a",
		"sphinx":        "src-8f53eed9c76c5c94",
		"sqlserver":     "src-6528f2e7b67cf9f7",
		"sqlite":        "src-23e84cc5a429d0b5",
		"duckdb":        "src-fefd68f047dbd5a6",
		"dameng":        "src-e69b7c9a9c897ccd",
		"kingbase":      "src-48642a500484b799",
		"highgo":        "src-9ed88d6723301100",
		"vastbase":      "src-37f72792828c9651",
		"opengauss":     "src-236e31de873676f7",
		"gaussdb":       "src-685094799a226f30",
		"iris":          "src-52206e6112a1a46c",
		"cache":         "src-b794443e46b7f784",
		"mongodb":       "src-0f4643d2f9822679",
		"tdengine":      "src-5b96116a899d4387",
		"iotdb":         "src-686443bc6cca4e62",
		"clickhouse":    "src-1a3882e10d01e9e4",
		"elasticsearch": "src-fc3da3f3e10bda2c",
		"trino":         "src-073d1cda565a2dae",
	}
}
